CREATE TABLE students (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255)
);

CREATE TABLE courses (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(10),
	name VARCHAR(255)
);

CREATE TABLE ratings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	student INTEGER,
	course INTEGER,
	FOREIGN KEY (student) REFERENCES students(id),
	FOREIGN KEY (course) REFERENCES courses(id)
)