CREATE TABLE students (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE courses (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	code VARCHAR(10) UNIQUE NOT NULL,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE ratings (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	student INTEGER NOT NULL,
	course INTEGER NOT NULL,
	rating INTEGER NOT NULL,
	FOREIGN KEY (student) REFERENCES students(id),
	FOREIGN KEY (course) REFERENCES courses(id)
)